import React, { useState } from "react";
import { 
  Video, 
  Film, 
  Play, 
  Pause, 
  Sparkles, 
  Subtitles, 
  Mic2, 
  UserCheck, 
  Download, 
  RefreshCw,
  Layers,
  Volume2
} from "lucide-react";
import { VideoProjectItem } from "../types";

export const VideoStudioWorkspace: React.FC = () => {
  const [prompt, setPrompt] = useState("");
  const [avatarName, setAvatarName] = useState("Hariom HK AI Avatar");
  const [aspectRatio, setAspectRatio] = useState<"16:9" | "9:16">("16:9");
  const [mode, setMode] = useState<"text_to_video" | "avatar_video" | "subtitles" | "dubbing">("text_to_video");
  const [isLoading, setIsLoading] = useState(false);
  const [isPlaying, setIsPlaying] = useState(false);

  const [videoProjects, setVideoProjects] = useState<VideoProjectItem[]>([
    {
      id: "vid-demo-1",
      title: "HK Nexus Studio AI Future Intro",
      prompt: "A cinematic high-tech hologram logo revealing HK Nexus AI created by Hariom Kushwaha in 8k cyber city",
      status: "completed",
      videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4",
      aspectRatio: "16:9",
      subtitles: ["Welcome to HK Nexus Studio AI", "Created by Hariom Kushwaha Mauranipur", "Next Generation AI Ecosystem"],
      dubbingLanguage: "Hindi & English",
      durationSeconds: 15
    }
  ]);

  const [activeProject, setActiveProject] = useState<VideoProjectItem>(videoProjects[0]);

  const handleCreateVideo = async () => {
    if (!prompt.trim()) return;
    setIsLoading(true);

    setTimeout(() => {
      const newProj: VideoProjectItem = {
        id: `vid-${Date.now()}`,
        title: prompt.slice(0, 30) || "HK AI Video Scene",
        prompt: prompt,
        status: "completed",
        videoUrl: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4",
        aspectRatio: aspectRatio,
        subtitles: ["Generated by HK Nexus Video AI", "Hariom Kushwaha (HK Tech World)", "Auto Subtitles synchronized"],
        dubbingLanguage: "Hindi AI Voice",
        durationSeconds: 12
      };

      setVideoProjects((prev) => [newProj, ...prev]);
      setActiveProject(newProj);
      setIsLoading(false);
    }, 2500);
  };

  return (
    <div className="max-w-6xl mx-auto px-3 sm:px-4 py-4">
      {/* Header */}
      <div className="mb-4 bg-slate-900 p-4 rounded-2xl border border-slate-800 shadow-sm flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-base font-bold text-white flex items-center gap-2">
            <Video className="w-5 h-5 text-cyan-400" />
            <span>Video AI Studio</span>
          </h2>
          <p className="text-xs text-slate-400 mt-0.5">
            Text-to-Video, AI Avatar presenter, and auto subtitles
          </p>
        </div>

        {/* Mode Selector */}
        <div className="flex flex-wrap items-center gap-1 bg-slate-950 p-1 rounded-xl border border-slate-800 text-xs">
          {[
            { id: "text_to_video", label: "🎥 Text to Video" },
            { id: "avatar_video", label: "👤 Avatar" },
            { id: "subtitles", label: "💬 Subtitles" },
            { id: "dubbing", label: "🎙️ Dubbing" },
          ].map((m) => (
            <button
              key={m.id}
              onClick={() => setMode(m.id as any)}
              className={`px-2.5 py-1 rounded-lg text-xs font-medium transition-all ${
                mode === m.id
                  ? "bg-cyan-600 text-white font-semibold"
                  : "text-slate-400 hover:text-slate-200"
              }`}
            >
              {m.label}
            </button>
          ))}
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Controls */}
        <div className="bg-slate-900/90 rounded-3xl p-6 border border-slate-800 shadow-lg space-y-5">
          <h3 className="text-sm font-bold text-white flex items-center gap-2">
            <Film className="w-4 h-4 text-cyan-400" />
            <span>Video Storyboard & Voice Config</span>
          </h3>

          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5">
              Video Scene Prompt or Script
            </label>
            <textarea
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
              placeholder="Describe the video scene or avatar script (e.g., Hariom Kushwaha introducing HK Nexus AI in a futuristic studio)..."
              rows={4}
              className="w-full bg-slate-950 border border-slate-800 rounded-2xl p-3 text-xs text-white placeholder-slate-500 focus:outline-none focus:border-cyan-500"
            />
          </div>

          {/* Aspect Ratio */}
          <div>
            <label className="block text-xs font-semibold text-slate-300 mb-1.5">Aspect Ratio</label>
            <div className="grid grid-cols-2 gap-2">
              <button
                onClick={() => setAspectRatio("16:9")}
                className={`py-2 rounded-xl text-xs font-semibold border ${
                  aspectRatio === "16:9"
                    ? "bg-cyan-600 border-cyan-400 text-white"
                    : "bg-slate-950 border-slate-800 text-slate-400"
                }`}
              >
                16:9 (Landscape YouTube)
              </button>
              <button
                onClick={() => setAspectRatio("9:16")}
                className={`py-2 rounded-xl text-xs font-semibold border ${
                  aspectRatio === "9:16"
                    ? "bg-cyan-600 border-cyan-400 text-white"
                    : "bg-slate-950 border-slate-800 text-slate-400"
                }`}
              >
                9:16 (Vertical Reels/Shorts)
              </button>
            </div>
          </div>

          {mode === "avatar_video" && (
            <div>
              <label className="block text-xs font-semibold text-slate-300 mb-1.5">Select AI Presenter Avatar</label>
              <select
                value={avatarName}
                onChange={(e) => setAvatarName(e.target.value)}
                className="w-full bg-slate-950 border border-slate-800 rounded-xl p-2.5 text-xs text-white focus:outline-none focus:border-cyan-500"
              >
                <option value="Hariom HK AI Avatar">Hariom HK AI Avatar (Creator Mode)</option>
                <option value="Alex Tech Anchor">Alex - Tech Anchor (Male)</option>
                <option value="Sophia Global Presenter">Sophia - Global Presenter (Female)</option>
              </select>
            </div>
          )}

          <button
            onClick={handleCreateVideo}
            disabled={isLoading}
            className="w-full py-3 rounded-2xl bg-gradient-to-r from-cyan-600 via-indigo-600 to-purple-600 text-white font-bold text-sm shadow-xl shadow-cyan-500/25 hover:opacity-90 transition-all flex items-center justify-center space-x-2"
          >
            {isLoading ? (
              <>
                <RefreshCw className="w-5 h-5 animate-spin" />
                <span>Generating HK AI Video...</span>
              </>
            ) : (
              <>
                <Sparkles className="w-5 h-5" />
                <span>Synthesize Video Project</span>
              </>
            )}
          </button>
        </div>

        {/* Display & Player */}
        <div className="lg:col-span-2 space-y-6">
          <div className="bg-slate-900/90 rounded-3xl p-6 border border-slate-800 shadow-lg space-y-4">
            <div className="flex items-center justify-between">
              <h3 className="text-sm font-bold text-white flex items-center gap-2">
                <Video className="w-4 h-4 text-cyan-400" />
                <span>{activeProject.title}</span>
              </h3>
              <span className="px-2.5 py-0.5 rounded-full bg-cyan-950 text-cyan-300 border border-cyan-500/30 text-[10px] font-mono">
                HD 1080p • {activeProject.durationSeconds}s
              </span>
            </div>

            {/* Video Player */}
            <div className="relative rounded-2xl overflow-hidden border border-slate-800 bg-slate-950 aspect-video flex items-center justify-center">
              {activeProject.videoUrl ? (
                <video
                  src={activeProject.videoUrl}
                  controls
                  className="w-full h-full object-cover"
                />
              ) : (
                <p className="text-xs text-slate-500">Video project processing...</p>
              )}
            </div>

            {/* Subtitle Stream Overlay */}
            {activeProject.subtitles && activeProject.subtitles.length > 0 && (
              <div className="bg-slate-950 p-4 rounded-2xl border border-slate-800">
                <h4 className="text-xs font-bold text-cyan-400 flex items-center gap-1.5 mb-2">
                  <Subtitles className="w-4 h-4" /> Auto-Generated Subtitles & Script
                </h4>
                <div className="space-y-1">
                  {activeProject.subtitles.map((sub, idx) => (
                    <p key={idx} className="text-xs text-slate-300 font-mono">
                      <span className="text-cyan-500 font-bold">[{idx * 4}s]</span> {sub}
                    </p>
                  ))}
                </div>
              </div>
            )}
          </div>
        </div>
      </div>
    </div>
  );
};
